### ISSUE TITLE
Support for hls offline drm

### ISSUE THREAD

**Issue by fuzing** [kaltura/playkit-dtg-ios#36]
Is there a roadmap for implementing offline playback with fairplay drm.
Any ETA info would be greatly appreciated.
Cheers and thanks.

**Comment by kaltura-hooks** [comment]
Hi @fuzing,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by noamtamim** [comment]
@fuzing FairPlay has to be supported by the player, not the download manager. Our Player SDK (PlayKit) supports offline FairPlay.

**Comment by fuzing** [comment]
Hi Noam:

Thanks for the feedback.   I guess I'm confused.   I figured that one
should be able to use the download manager to download keys in advance of
playback (i.e. before going offline for a week, for example).   I didn't
see a mechanism for doing this using playkit (IOS) itself.   My
understanding of playkit is that the AVPlayer instance itself will initiate
retrieval of keys when it needs them (which might be when the user is
already offline).

Our use case includes the requirement for checking that content-keys will
be valid in 'n' days time, and if not then refreshing them.   Is this
possible using playkit and/or the download manager?

Thanks for your time,

Regards

**Comment by noamtamim** [comment]
The PlayKit guide that refers to offline playback (and in particular, with FairPlay) is here:
https://kaltura.github.io/playkit/guide/ios/core/offline.html

The class referred to in that guide is here: 
https://kaltura.github.io/playkit/api/ios/core/Classes/LocalAssetsManager.html

Note that our documentation is going through a major overhaul and will soon be migrated to a new platform, but the above is currently the most up-to-date guide.

**Comment by fuzing** [comment]
Perfect - Thanks so much for this, and for your quick response.
