### ISSUE TITLE
Other downloaded videos URL not played offline

### ISSUE THREAD

**Issue by JayCears** [kaltura/playkit-dtg-ios#51]
Hello **@x-NR-x,**

I hope you are doing well. I am facing one issue in your library.

Firstly, I am getting errors while pod installation for solving that issue I did comment on some codes and change some values which you can check in bellowed images and it seems perfectly played of downloaded video online as well as offline mode.

I created a new demo and downloaded my video URL, it's played well online but not played well offline

**My content URL is:-** https://rg-tv.com/storage/movies/Stuber/YYYtPmPWRUT9tHMvQE6A.m3u8

Can you give me some solutions to this issue?

Thanks in advance.
:)

![Screen Shot 2019-11-04 at 11 44 43 AM](https://user-images.githubusercontent.com/57251376/68103582-7be07780-fefd-11e9-9797-8bf16761e1f3.png)

![Screen Shot 2019-11-04 at 11 45 05 AM](https://user-images.githubusercontent.com/57251376/68103586-81d65880-fefd-11e9-845c-a9149572d1af.png)

![Screen Shot 2019-11-04 at 11 44 56 AM](https://user-images.githubusercontent.com/57251376/68103588-84d14900-fefd-11e9-8d30-181566f430a4.png)

![Screen Shot 2019-11-04 at 2 12 48 PM](https://user-images.githubusercontent.com/57251376/68108253-4a6fa800-ff0d-11e9-806d-898ebeb4b01e.png)

**Comment by x-NR-x** [comment]
Hi @JayCears,

Thank you for contacting us.

You can check out the [Example](https://github.com/kaltura/playkit-ios-dtg/tree/develop/Example) provided in the repo for reference.
I set the provided url you wrote (https://rg-tv.com/storage/movies/Stuber/YYYtPmPWRUT9tHMvQE6A.m3u8) in the example and it worked fine playing in offline mode after downloading.

Regarding the pod installation issue, what Swift version are you working with?
From DownloadToGo v3.8 only Swift 5 is supported because of 3rd party pods which are used.

Thanks,
Nilit Danan

**Comment by noamtamim** [comment]
@JayCears please reopen if still relevant.
