### ISSUE TITLE
Xcode 14.1 compile error

### ISSUE THREAD

**Issue by olliestringfield-accedo** [kaltura/playkit-dtg-ios#87]
**Describe the bug**
When building that latest DTG 3.18.0 using Xcode 14.1 or later, we receive a compile error regarding RealmSwift

**To Reproduce**
Add DTG using cocoapods, build the app

**Expected behavior**
Build to compile with no errors

**Logs and Screenshots**
`Undefined symbols for architecture arm64:
  "_$s10RealmSwift0A14CollectionImplPAAE12makeIteratorAA11RLMIteratorVy7ElementQzGyF", referenced from:
      _$s12DownloadToGo12migrate_to_333_04D983CE8B87C002D73D729D97DFFAD1LLyy10RealmSwift9MigrationVFyAD13DynamicObjectCSg_AItXEfU_ in DB.o
  "_$s10RealmSwift4ListCyxGAA0A14CollectionImplAAMc", referenced from:
      _$s10RealmSwift4ListCyAA13DynamicObjectCGACyxGAA0A14CollectionImplAAWl in DB.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Platform**
 - OS and version: N/A
 - Device type: N/A
 - Library version 3.18.0

**Additional context**
I believe this is an error in the RealmSwift framework and has been fixed in 10.32.2
https://github.com/realm/realm-swift/releases/tag/v10.32.2
Apple requires all apps uploaded to the Appstore after April 1st to be built using Xcode 14.1 or later

**Comment by giladna** [comment]
@olliestringfield-accedo 
I am using Xcode 14.2

I was installing the demo app based on 13.8.0 and I got Installing Realm (10.32.3) and app running ok

please check your comment regarding 10.32.2
please check your Pod file
seems there is no issue.

./iOS/kaltura/playkit-ios-dtg/Example> pod install --repo-update
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Updating local specs repositories

CocoaPods 1.12.0 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.12.0

Analyzing dependencies
Downloading dependencies
Installing DownloadToGo (3.18.0.0000)
Installing GCDWebServer (3.5.4)
Installing KalturaNetKit (1.6.1)
Installing M3U8Kit (1.0.0)
Installing ObjcExceptionBridging (1.0.1)
Installing PlayKit (3.27.2)
Installing PlayKitProviders (1.18.2)
Installing PlayKitUtils (0.5.1)
Installing Realm (10.32.3)
Installing RealmSwift (10.32.3)
Installing SwiftyJSON (5.0.0)
Installing SwiftyXMLParser (5.0.0)
Installing Toast (4.0.0)
Installing XCGLogger (7.0.0)
Generating Pods project

FYI
@x-NR-x

**Comment by olliestringfield-accedo** [comment]
@giladna 
Oh yes I see now the podspec for DTG uses the optimistic operator to specify RealmSwift `'RealmSwift', '~> 10.32.0'` allowing any minor version.
We were specifying 10.32.0 which contained the issue. I have upgraded to 10.32.3 which includes the fix and can verify the compile error is fixed.
Thanks
